version: '3.5'

services:
  odyfo-cakephp-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: odyfo-cakephp-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8009:80
  odyfo-mysql-db:
    image: mysql:5.7
    container_name: odyfo-mysql-db
    volumes:
      - ./_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=dbodyfo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=master
  mysql-adminer :
    depends_on:
      - odyfo-mysql-db
    image : adminer
    ports :
      - 8089:8080
